CREATE TABLE IF NOT EXISTS profiles (
  sub TEXT PRIMARY KEY,
  sensitivity DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  volume DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  crosshair_color TEXT NOT NULL DEFAULT '#00ff00',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);